services:
  # The Backend Node.js API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: herank_api
    restart: always
    ports:
      - '5000:5000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    depends_on:
      - postgres
    networks:
      - herank-network

  # Prisma Studio Service
  studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: herank_studio
    restart: always
    command: npx prisma studio --port 5555 --browser none
    ports:
      - '5555:5555'
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    depends_on:
      - postgres
    networks:
      - herank-network

  # The Postgres Database
  postgres:
    image: postgres:15-alpine
    container_name: herank_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - herank-network

networks:
  herank-network:
    driver: bridge

volumes:
  pgdata: